# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20170720_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='src',
            field=models.URLField(default='http'),
            preserve_default=False,
        ),
    ]
