# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_trip_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='src',
            field=models.URLField(null=True),
        ),
    ]
