language: python
python:
  - "3.6.1"

install:
  - pip install -r requirements.txt
  - pip install codecov
cache: pip

services:
  - postgresql
before_script:
  - psql -c 'create database travis;' -U postgres

script:
  - cd myTrip/
  - pylint --rcfile=.pylintrc registration/views.py
  - pylint --rcfile=.pylintrc registration/models.py
  - coverage run --source=registration manage.py test tests/unittests/registration

after_success:
 - codecov 
