language: python
python:
  - "3.6.1"

install:
  - pip install -r requirements.txt
  - pip install coveralls
cache: pip

services:
  - postgresql
before_script:
  - psql -c 'create database travis;' -U postgres

script:
  - cd myTrip/
  - pylint --rcfile=.pylintrc *
  - coverage run manage.py test

after_success:
 - coveralls
