postgres:
  restart: always
  image: postgres:9.4
  ports:
    - "5432:5432"
  expose:
    - "5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=postgres

web:
  build: .
  restart: always
  ports:
    - "8000:8000"
  expose:
    - "8000"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=postgres
  links:
    - postgres
  command: 
    - ./db/boot.sh
  stdin_open: true
  tty: true
