# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 21, 13, 4, 394595))),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 21, 13, 4, 394712))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
