# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_modified',
            field=models.DateTimeField(default=None),
        ),
    ]
