# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170808_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
