# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20170713_1314'),
        ('photo', '0001_initial'),
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='checkpoint',
            field=models.ManyToManyField(to='checkpoint.Checkpoint'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ManyToManyField(to='photo.Photo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='trip',
            field=models.ManyToManyField(to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
