# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20170810_1217'),
        ('comment', '0006_auto_20170808_1611'),
    ]

    operations = [
    ]
