# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20170726_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.URLField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.TextField(null=True)),
                ('hobbies', models.TextField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('google', models.URLField(null=True)),
            ],
        ),
    ]
