# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/media/'),
        ),
    ]
