# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='/static/src/img/avatar.png', null=True),
        ),
    ]
