# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In progress'), ('Annonced', 'Annonced'), ('Finished', 'Finished')], default='InProgress', max_length=200),
        ),
    ]
