# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('position_number', models.IntegerField()),
                ('source_url', models.URLField()),
                ('created', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
            ],
        ),
    ]
