# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
        ('checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
    ]
