# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20170718_1335'),
        ('trip', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
    ]
