# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20170713_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='created',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 15, 57, 9, 139441)),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 15, 57, 9, 139492)),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='trip',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
            preserve_default=False,
        ),
    ]
