# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20170713_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='trip_id',
        ),
    ]
