# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0003_auto_20170718_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='create_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='update_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
