# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('trip', models.IntegerField(null=True)),
                ('checkpoint', models.IntegerField(null=True)),
                ('photo', models.IntegerField(null=True)),
                ('comment', models.IntegerField(null=True)),
            ],
        ),
    ]
