# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('trip', '0002_auto_20170718_1501'),
        ('checkpoint', '0002_auto_20170712_1325'),
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoint.Checkpoint')),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
