# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='checkpoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='trip',
            field=models.IntegerField(null=True),
        ),
    ]
