# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20170718_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoint.Checkpoint'),
        ),
    ]
