# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20170718_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
