# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_auto_20170808_1126'),
        ('like', '0004_auto_20170808_1734'),
    ]

    operations = [
    ]
