# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='response_message',
            field=models.TextField(blank=True),
        ),
    ]
