# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
                ('user_id', models.IntegerField()),
                ('trip_id', models.IntegerField(null=True)),
                ('checkpoint_id', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
