# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170720_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
