# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_merge_20170810_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoint.Checkpoint'),
        ),
    ]
